Zomato/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import zomato
from Zomato import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('zomato.urls')),
]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zomato/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Zomato import settings
from zomato import views
app_name = 'zomato'
urlpatterns = [
    path('',views.homeview,name='homeview'),
    path('user_login/',views.user_login, name = 'user_login'),
    path('user_logout/',views.user_logout, name = 'user_logout'),
    path('register/',views.register, name = 'register'),
    url(r'^hotel=(?P<hotel_id>[-\w]+)/$',views.hotelview, name = 'hotelview'),
    url(r'^cart=(?P<user_id>[-\w]+)/$',views.cartview, name = 'cartview'),
    url(r'^checkout=(?P<user_id>[-\w]+)/$',views.checkout, name = 'checkout'),
    url(r'^orders/$',views.orderview, name = 'orderview'),
    url(r'^profile/$',views.user_profile, name = 'user_profile'),
    url(r'^hotels/$',views.hotels, name = 'hotels'),
    url(r'^dishes/$',views.dishes, name = 'dishes'),
]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zomato/models.py
import uuid
from datetime import datetime

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models

# Create your models here.
from django.utils.timezone import now
from multiselectfield import MultiSelectField
from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase




class UserManager(BaseUserManager):

    def create_user(self,username,name,password=None):
        if not username:
            raise ValueError("Please enter an username")

        user = self.model(
            username = username
        )
        user.set_password(password)
        user.name = name
        user.save(using=self._db)
        return user

    def create_superuser(self,username,name,password):
        user = self.create_user(username,name, password=password)
        user.admin = True
        user.staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    name = models.CharField(max_length=255, blank=False)
    username = models.CharField(max_length=255, blank=False, unique=True)
    user_id = models.UUIDField(unique=True, default=uuid.uuid4)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.BigIntegerField(blank=True,null=True)
    category = models.CharField(max_length=255, default='Customer')
    sector = models.IntegerField(blank=True, null=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name']

    objects = UserManager()


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_customer(self):
        return self.category.lower() == 'customer'

    @property
    def is_vendor(self):
        return self.category.lower() == 'vendor'

    @property
    def is_delivery_agent(self):
        return self.category.lower() == 'delivery'

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_staff(self):
        return self.staff

class Hotel(models.Model):
    vendor = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel_id = models.UUIDField(unique=True, default=uuid.uuid4)
    name = models.CharField(max_length=255, blank=False, null=False)
    sector = models.IntegerField()
    photo = models.ImageField(upload_to='hotel_photos',null=True)

    def __str__(self):
        return self.name

class Dish(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    dish_id = models.UUIDField(unique=True, default=uuid.uuid4)
    name = models.CharField(max_length=255)
    veg = models.BooleanField()
    price = models.IntegerField()
    photo = models.ImageField(upload_to='dish_photos', null=True)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Dish, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='customer')
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    transaction_id = models.UUIDField(unique=True, default=uuid.uuid4)
    price = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)
    duration = models.IntegerField()
    status = models.CharField(null=True, max_length=255)
    delivery = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

class Delivery(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    busy = models.BooleanField(default=False)
    order = models.ForeignKey(Cart,on_delete=models.SET_NULL,null=True, related_name='+')

zomato/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.forms import TextInput
from django import forms

from zomato.models import User, Hotel, Dish

MY_CATEGORIES = (
                ('Customer','Customer'),
                ('Vendor','Vendor'),
                ('Delivery','Delivery'),
                )



class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label="Password",widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password",widget=forms.PasswordInput)
    category = forms.CharField(label='Category', widget=forms.Select(choices = MY_CATEGORIES))

    name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    email = forms.EmailField(label="Email", widget=forms.EmailInput(
        attrs={
            'class': 'form-control'
        }
    ))

    username = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))


    class Meta:
        model = get_user_model()
        fields = ('name','username','email','category','sector','phone')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is already taken")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        if self.clean_email() and self.clean_password2():
            user = super(RegisterForm, self).save(commit=False)
            user.set_password(self.cleaned_data.get('password1'))
            if commit:
                user.save()
            return user
        else:
            raise ValueError("Error in form")

class LoginForm(forms.Form):
    email = forms.EmailField(label="Email",widget=forms.EmailInput(
        attrs={
            'class':'form-control'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class':'form-control'
        }
    ),label="Password")

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        user_final = User.objects.filter(
            Q(email__iexact = email)
        ).distinct()

        if not user_final.exists() and user_final.count() != 1:
            raise forms.ValidationError("Invalid credentials. User does not exist")

        user_obj = user_final.first()
        if not user_obj.check_password(password):
            raise forms.ValidationError("Password incorrect")

        self.cleaned_data['user_obj'] = user_obj
        return super(LoginForm, self).clean()

class HotelForm(forms.ModelForm):
    name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    sector = forms.IntegerField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    class Meta:
        model = Hotel
        fields = ('name','sector','photo')

class MenuForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ('name','veg','price')

zomato/views.py
from random import randint

from django.contrib.auth import logout, login
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from zomato.forms import RegisterForm, LoginForm, HotelForm, MenuForm
from zomato.models import Hotel, Dish, Transaction, User, Cart, Delivery



def homeview(request):
    if request.user.is_authenticated and request.user.is_vendor:
        hts = Hotel.objects.filter(vendor=request.user)
        if not hts:
            if request.method == 'POST':
                form = HotelForm(request.POST, request.FILES)
                if form.is_valid():
                    hotel = form.save(commit=False)
                    hotel.vendor = request.user
                    hotel.save()
                    return redirect('zomato:homeview')
            form = HotelForm()
            return render(request, 'zomato/hotelform.html', {'form': form})

        received_orders = Cart.objects.filter(hotel = Hotel.objects.get(vendor=request.user),status='placed')
        if received_orders:
            itemlist = []
            for order in received_orders:
                items =[]
                txns = Transaction.objects.filter(user=order.user, item__hotel=Hotel.objects.get(vendor=request.user))
                print(txns.count())
                for txn in txns:
                    items.append(txn.item)
                itemlist.append(items)
            print(itemlist)
            lists = zip(received_orders,itemlist)
            if request.method == 'POST':
                    order_id = request.POST['order-id']
                    o = Cart.objects.get(transaction_id=order_id)
                    o.status = 'accepted' if 'accept' in request.POST else 'rejected'
                    o.save()
                    if o.status == 'accepted':
                        delivery_boy = Delivery.objects.filter(busy=False, available=True).order_by('?').first()
                        o.delivery = delivery_boy.user
                        o.status = 'on its way'
                        delivery_boy.order = o
                        delivery_boy.available = False
                        delivery_boy.busy = True
                        o.save()
                        delivery_boy.save()
                        return redirect('/')
                    return redirect('/')
            return render(request,'zomato/homepage.html',{'lists':lists})
        else:
            return render(request, 'zomato/homepage.html',{'your_hotels':hts})
    elif request.user.is_authenticated and request.user.is_customer:
        hotels = Hotel.objects.all()
        dishes = Dish.objects.all()
        orders = Cart.objects.filter(user = request.user)
        return render(request, 'zomato/homepage.html', {'hotels':hotels,'dishes':dishes,'orders':orders})

    elif request.user.is_authenticated and request.user.is_delivery_agent:
        your_orders = Delivery.objects.filter(user=request.user,order__status__iexact='on its way')
        if request.method == 'POST':
            if 'deliver' in request.POST:
                order = Cart.objects.get(transaction_id=request.POST['order-id'])
                order.status = 'delivered'
                order.save()
                order.delete()
                Transaction.objects.filter(user = order.user, item__hotel=order.hotel).delete()
                return redirect('/')

        return render(request,'zomato/homepage.html',{'your_orders':your_orders})

    else: return render(request,'zomato/homepage.html')


def user_logout(request):
    logout(request)

    return render(request, 'zomato/homepage.html')

def user_login(request):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            user_obj = form.cleaned_data.get('user_obj')
            login(request,user_obj)
            if request.user.category == 'Delivery':
                delivery = Delivery.objects.get_or_create(user = request.user)
                return redirect('zomato:homeview')
            return redirect('zomato:homeview')
        return render(request, 'zomato/login.html', {'form':form})

def register(request):
    if request.method == 'POST' and 'submit' in request.POST:
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()

            return redirect('zomato:homeview')
        else:
            return HttpResponse('{}'.format(form.errors))
    form = RegisterForm()
    return render(request, 'zomato/register.html',{'form':form})


def hotelview(request,hotel_id):
    hotel = Hotel.objects.get(hotel_id=hotel_id)
    if request.POST:
        if 'add-dish' in request.POST:
            form = MenuForm(request.POST or None)
            if form.is_valid():
                menu = form.save(commit=False)
                menu.hotel = hotel
                menu.save()
                return redirect('zomato:homeview')
        elif 'add-to-cart' in request.POST:
            if request.user.is_authenticated:
                dish = Dish.objects.get(dish_id=request.POST['dish'])
                qty = request.POST['quantity']
                txn = Transaction(item=dish, user= request.user,quantity=qty)
                txn.save()
                return redirect('zomato:homeview')
            else:
                return redirect('zomato:homeview')

    dishes = Dish.objects.filter(hotel = hotel)
    form = MenuForm()
    return render(request, 'zomato/hotelview.html',{'dishes':dishes,'hotel':hotel,'form':form})

def cartview(request,user_id):
    if request.method == 'POST':
        if 'remove' in request.POST:
            item_id = request.POST['item']
            Transaction.objects.filter(item=Dish.objects.get(id=item_id),user=request.user).first().delete()
            return redirect('/')


    user = User.objects.get(user_id = user_id)
    txns = Transaction.objects.filter(user = user)
    total = 0
    for txn in txns: total+= (txn.item.price*txn.quantity)
    return render(request, 'zomato/cartview.html',{'txns':txns,'total':total,'user':user})

def checkout(request,user_id):
    user = User.objects.get(user_id= user_id)
    txns = Transaction.objects.filter(user=user)
    total = 0
    for txn in txns: total += (txn.item.price*txn.quantity)
    duration = 20 +  ((user.sector - txns[0].item.hotel.sector)%4)*10
    if request.method == 'POST':
        if 'place-order' in request.POST:
            Cart(user = user, price = total, duration = duration, status='placed',hotel= txns[0].item.hotel).save()
            return redirect('zomato:homeview')


    return render(request, 'zomato/checkout.html',{'total':total, 'duration':duration,'txns':txns,'sector':user.sector})

def orderview(request):
    orders = Cart.objects.filter(user=request.user)
    return render(request, 'zomato/orderview.html',{'orders':orders})

def user_profile(request):
    return render(request, 'zomato/profile.html',{'user':request.user})

def hotels(request):
    hotels = Hotel.objects.all()
    return render(request, 'zomato/hotels.html',{'hotels':hotels})

def dishes(request):
    dishes = Dish.objects.all()
    return render(request, 'zomato/dishes.html',{'dishes':dishes})

zomato/templates/zomato/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hi }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'zomato:homeview' %}">FoodJunction</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'zomato:homeview' %}">Home</a></li>

      <li><a href="#">Hotels</a></li>
      <li><a href="#">Dishes</a></li>
    </ul>
      {% if not user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'zomato:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'zomato:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'zomato:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      <li><a href="{% url 'zomato:cartview' user.user_id %}"><span class="glyphicon glyphicon-shopping-cart"></span> My Cart</a></li>
    </ul>
      {% endif %}
  </div>
</nav>
<br>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

</body>
</html>

zomato/templates/zomato/cartview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Cart | FoodJunction</title>
</head>
<body>

<div class="container">
    <ul type="None">
        {% for txn in txns %}
            <li><p style="float: left">{{ txn.item.name }}</p><p style="float: right">${{ txn.item.price }}</p></li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

zomato/templates/zomato/dishes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dishes</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>

<div class="container">
        <div class="well well-lg">
        <h1>Dishes: </h1>
        </div>
        <div class="row">
        {% for dish in dishes %}

            <div class="column">
    <div class="card" style="text-align: center;border-top-left-radius: 10px; border-top-right-radius: 10px">

      <div class="container">
        <h2><a style="color: #4285F4" href = "{% url 'zomato:hotelview' dish.hotel.hotel_id %}">{{dish.name }}</a></h2>

        <p class="title">${{ dish.price}}</p>

      </div>
    </div>
  </div>

        {% endfor %}
        </div>


        </div>

</body>
</html>

zomato/templates/zomato/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hi }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


    <style>
        body{
            overflow-x: hidden;
        }

 html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}
    </style>


</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0; background-color: #4285F4; color: white">
  <h1 style="padding: 5px">FoodJunction</h1>
  <p>Where satisfaction meets your soul</p>
</div>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'zomato:homeview' %}">FoodJunction</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>

      <li><a href="{% url 'zomato:hotels' %}">Hotels</a></li>
      <li><a href="{% url 'zomato:dishes' %}">Dishes</a></li>
    </ul>
      {% if not user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'zomato:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'zomato:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'zomato:user_profile' %}"><span class="glyphicon glyphicon-user"></span>My Profile</a></li>
      <li><a href="{% url 'zomato:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      <li><a href="{% url 'zomato:cartview' user.user_id %}"><span class="glyphicon glyphicon-shopping-cart"></span> My Cart</a></li>
    </ul>
      {% endif %}
  </div>
</nav>


{% if orders %}

    <div class="container">
  <div class="panel panel-default">

    <div class="panel-heading"><a href="{% url 'zomato:orderview' %}">Your Orders</a></div>

  </div>
</div>

{% endif %}



{%if hotels%}

    <div class="container">
        <div class="well well-lg">
        <h1>Nearby Hotels: </h1>
        </div>
        <div class="row">
        {% for hotel in hotels %}

            <div class="column">
    <div class="card" style="border-top-left-radius: 10px; border-top-right-radius: 10px">
        <div style="display: inline-block">
      <img src="{{ hotel.photo.url }}" alt="profile-pic" style="width:200px; height: 200px; border-top-left-radius: 10px; border-top-right-radius: 10px">
            </div>
      <div class="container">
        <h2><a style="color: #4285F4" href = "{% url 'zomato:hotelview' hotel.hotel_id %}">{{ hotel.name }}</a></h2>

        <p class="title">{{ hotel.vendor.name }}</p>

        <p>Sector: {{ hotel.sector }}</p>

      </div>
    </div>
  </div>

        {% endfor %}
        </div>
        </div>

{% endif %}

{% if dishes %}

    <div class="container">
        <div class="well well-lg">
        <h1>Dishes: </h1>
        </div>
        <div class="row">
        {% for dish in dishes %}

            <div class="column">
    <div class="card" style="border-top-left-radius: 10px; border-top-right-radius: 10px">

      <div class="container">
        <h2><a style="color: #4285F4" href = "{% url 'zomato:hotelview' dish.hotel.hotel_id %}">{{dish.name }}</a></h2>

        <p class="title">${{ dish.price}}</p>

      </div>
    </div>
  </div>

        {% endfor %}
        </div>


        </div>


{% endif %}

{% if lists %}
    <div class="container">
    <ul>
    {% for order,items in lists %}
        <li>
        Order id : {{ order.transaction_id }}<br>
        Price : {{ order.price }}<br>
        Address : {{ order.user.sector }}<br>
        Duration : {{ order.duration }}<br>
            Hotel: {{ order.hotel.name }}<br>


            <div class="container">


  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" href="#collapse1" class="btn btn-warning">Items</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <ul class="list-group" type="None">
          {% for item in items %}
              <li>{{ item.name }}</li>
              {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>


<form method="post">
    {% csrf_token %}
    <input type="hidden" name="order-id" value="{{ order.transaction_id }}">
    <input type="submit" class="btn btn-success" name="accept" value="Accept">
    &nbsp;
    <input type="submit" class="btn btn-danger" name="reject" value="Reject">
    </form>
        </li>

    {% endfor %}
    </ul>
    </div>
{% endif %}

{% if your_hotels %}
                 <div class="container">
        <div class="well well-lg">
        <h1>Your Hotels: </h1>
        </div>
        <div class="row">
        {% for hotel in your_hotels %}

            <div class="column">
    <div class="card" style="border-top-left-radius: 10px; border-top-right-radius: 10px">
        <div style="display: inline-block">
      <img src="{{ hotel.photo.url }}" alt="profile-pic" style="width:100%; height: 300px; border-top-left-radius: 10px; border-top-right-radius: 10px">
            </div>
      <div class="container">
        <h2><a style="color: #4285F4" href = "{% url 'zomato:hotelview' hotel.hotel_id %}">{{ hotel.name }}</a></h2>

        <p class="title">{{ hotel.vendor.name }}</p>

        <p>Sector: {{ hotel.sector }}</p>

      </div>
    </div>
  </div>

        {% endfor %}
        </div>
        </div>
{% endif %}


{% if your_orders %}
    <ul>
    {% for your_order in your_orders %}
    <li>Order id : {{ your_order.order.transaction_id }}</li>
    <li>Price : {{ your_order.order.price }}</li>
    <li>Time: {{ your_order.order.duration }}</li>
    <li>Address : Sector {{ your_order.order.user.sector }}</li>
    <li><form method="post">{% csrf_token %}<input type="hidden" name="order-id" value="{{ your_order.order.transaction_id }}"><input class="btn btn-success" type="submit" name="deliver" value="Deliver"></form></li>
    {% endfor %}
    </ul>
{% endif %}

</body>
</html>

zomato/templates/zomato/hotels.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotels</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>


<div class="container">
        <div class="well well-lg">

        </div>
        <div class="row">
        {% for hotel in hotels %}

            <div class="column">
    <div class="card" style="text-align: center;border-top-left-radius: 10px; border-top-right-radius: 10px">
        <div style="display: inline-block">
      <img src="{{ hotel.photo.url }}" alt="profile-pic" style="width:100%; height: 300px; border-top-left-radius: 10px; border-top-right-radius: 10px">
            </div>
      <div class="container">
        <h2><a style="color: #4285F4" href = "{% url 'zomato:hotelview' hotel.hotel_id %}">{{ hotel.name }}</a></h2>

        <p class="title">{{ hotel.vendor.name }}</p>

        <p>Sector: {{ hotel.sector }}</p>

      </div>
    </div>
  </div>

        {% endfor %}
        </div>
        </div>



</body>
</html>

zomato/templates/zomato/orderview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your order</title>
</head>
<body>
<div class="container"></div>
<ul>
    {% for order in orders %}
        <li>
        <div>
            Order id: {{ order.transaction_id }}<br>
            Price: {{ order.price }}<br>
            Duration: {{ order.duration }}<br>
            Status : {{ order.status }}<br>
            Hotel : {{ order.hotel }}<br>
            </div>
        </li>
    {% endfor %}
</ul>
</div>
</body>
</html>